apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pihole-secrets
  namespace: pihole
spec:
  encryptedData:
    WEBPASSWORD: AgATwgPrlENcZ3g0kzJZWYFqPKXu3TrC8oiQGd+GKPD6jzqXlCpUBroj0w2v9aDxhpYrMkr6L1txFqJlHTqp6dIe1oe59aWYwE32oqidpRjZGVFa+A4dhCyEEVbqVwx7S+DP7lnoYfOC4jPEgA7q1BpnH3mt+pru7gcGaia7Tpn/cxb8Z7J+1uE6ipfGQZqDJMM0yk05QHzerG9kO9scb2Tce0OhMpTr+ZjeOzcw/wlxSDrltqVGxutI6j0efW3YmP5mXH02lRBjGC4yW0bYxH1Yn4T6kTel+2PioRV2JdFhReKod3ZwgoCOA5U0shV3/z2uQu6TAX3DjwafiTk87p748jfX0/nbXBwrLQecmbYXMH6CVIvgs0ymkdDBkuZbbOCFltm20GdRvyInkoH1Q2pspD3SsGlfBLRFCv+eKXUagCv+REfaPU44mNTwzlgaWYzh8hEIzCsd6d9tR0FOQ6/6r1Z9Uzpea9t4TW56oubY/hJ6oYGJCw5p8Ypy7R+LXBtNLUbOxOPcs6a7pydWJ37BnX/tyIhwH6s2i+sQBf/mKSij65O1o2qI4QgtIUC9mkWsvUii1dtIvgNRumYWkrcRjvao94kPYkQP7K+yB5/c05XyqJeR573OX5nyUbfrR+hTb9LPb303rMicGRHP4ak5fFc6WU2aJ/IWRJQB0FlBc9aYRlt3JAvlagObBL53+k7wueGrL4+Arjk=
  template:
    metadata:
      creationTimestamp: null
      name: pihole-secrets
      namespace: pihole
