apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pihole-secrets
  namespace: pihole
spec:
  encryptedData:
    WEB_PASSWORD: AgCENJ6fn1/TqfpAIJFBOy6SXLObh+iCg0zme7Ap7Dy227kkuGRghql4wetDbSWeS3r4pxYTvPY2bXpQyKKYsO8ZD/1AUD7VlpaP6KCGRVM91CZuf95fXfUVGLRa0E460MqVJ8mehL6jl5QpearrgyITGR2isjOQpXNWnlh5tNaZExSpL7R34Z2nFGo+dvCpyfDPpS/ojt/zUYR8sJKzMm9pDFocmGaGN2oL02wgjZwA2gc4JOF25nmMaUuBtHCGBIaTsu+yxkH/dN+OtcIUryAnY6MezAg/kW4UjHb8/4IHi4A0PtPd+om2+fl9bpm3tuchZvm//N53SCUPU32GVEUhiDlSd6zTRXluAwDpB+46yyTzCLW61/LA251xtoCIAqHVnxOeLdaqOdnL+Dd7DqinrChgKE9qBvqBhlwvCmPuC3AmJpoj4SOLcYPKOwFMS7vjuMT4vU+2hyq0RACuz0SwQCl6ZQjYdQttQjLzxJ4pGOw/Hm2KxH4aAaANvoWLXxfSVHz5D3ZwRmbI2BZE6qb1ckrL4ZDLD4NjUnM+M6tVqWYXVHLsFLzie+cHO0Zs7nFMMeJpSa8N7UA2Wd9QLAQ690eBvEPqAgApIpDWDW2X+PiZx6ZmEmMhzZshjxOPzwbM5oSQfm1r2/d9WEQAorOpv9hKWBX2aL9tabYNt/Jrg+YsqDubwVHywZ6SJfs7YxFpwttGB35G/DU=
  template:
    metadata:
      creationTimestamp: null
      name: pihole-secrets
      namespace: pihole
status: {}

