kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-prometheus
  namespace: monitoring
  # can skip this annotation if storageClass is 'default'
  annotations:
    storageClassName: "local-path"
    prometheusComponent: "true"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
