kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-grafana
  namespace: monitoring
  # can skip this annotation if storageClass is 'default'
  annotations:
    storageClassName: "local-path"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
