kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-test-claim
  namespace: default
spec:
  # can skip this annotation if storageClass you want is 'default'
  #storageClassName: "local-path"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
